version: '3'
services:
    cough-recognition:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./sound_recognition:/app/sound_recognition